# Generated by Django 5.1.7 on 2025-03-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("consentbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsent",
            name="consent_script",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_consents",
                to="consentbot.consentscript",
            ),
            preserve_default=False,
        ),
    ]
