# Generated by Django 5.1.7 on 2025-03-25 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userconsent_consent_script"),
        ("consentbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconsent",
            name="consent_script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_consents",
                to="consentbot.consentscript",
            ),
        ),
    ]
