# Generated by Django 5.1.7 on 2025-03-25 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_userconsent_consent_script"),
        ("consentbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consent_script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="consentbot.consentscript",
            ),
        ),
    ]
