# Generated by Django 5.1.7 on 2025-03-30 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_consent_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
