# Generated by Django 5.0.1 on 2025-03-24 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsentScript",
            fields=[
                (
                    "consent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version_number", models.IntegerField()),
                ("script", models.JSONField()),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="consentbot.consentscript",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "version_number")},
            },
        ),
    ]
