# Generated by Django 5.2 on 2025-04-22 13:45

import consentbot.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentCache",
            fields=[
                (
                    "key",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ConsentScript",
            fields=[
                (
                    "script_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version_number", models.IntegerField()),
                ("script", models.JSONField()),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="consentbot.consentscript",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "user_consent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_age_group",
                    models.CharField(
                        choices=[
                            ("<=6", "<=6"),
                            ("7-17", "7-17"),
                            (">=18", ">=18"),
                            (">=18 guardianship", ">=18 guardianship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("store_sample_this_study", models.BooleanField(default=True)),
                ("store_sample_other_studies", models.BooleanField(default=False)),
                ("store_phi_this_study", models.BooleanField(default=True)),
                ("store_phi_other_studies", models.BooleanField(default=False)),
                ("return_primary_results", models.BooleanField(default=False)),
                (
                    "return_actionable_secondary_results",
                    models.BooleanField(default=False),
                ),
                ("return_secondary_results", models.BooleanField(default=False)),
                ("consent_statements", models.TextField(default="")),
                (
                    "user_full_name_consent",
                    models.CharField(default="", max_length=200),
                ),
                (
                    "child_full_name_consent",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dependent_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consent_script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to="consentbot.consentscript",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentTest",
            fields=[
                (
                    "user_test_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_try_num", models.IntegerField(blank=True, default=1, null=True)),
                ("test_question", models.CharField(max_length=200)),
                ("user_answer", models.CharField(max_length=200)),
                ("answer_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consent_script_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to="consentbot.consentscript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentUrl",
            fields=[
                (
                    "consent_url_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consent_url", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=consentbot.models.default_expiry),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_urls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
