# Generated by Django 5.0.1 on 2025-06-01 12:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentScript",
            fields=[
                (
                    "script_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version_number", models.IntegerField()),
                ("script", models.JSONField()),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="consentbot.consentscript",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "user_consent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_age_group",
                    models.CharField(
                        choices=[
                            ("<=6", "<=6"),
                            ("7-17", "7-17"),
                            (">=18", ">=18"),
                            (">=18 guardianship", ">=18 guardianship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("store_sample_this_study", models.BooleanField(default=True)),
                ("store_sample_other_studies", models.BooleanField(default=False)),
                ("store_phi_this_study", models.BooleanField(default=True)),
                ("store_phi_other_studies", models.BooleanField(default=False)),
                ("return_primary_results", models.BooleanField(default=False)),
                (
                    "return_actionable_secondary_results",
                    models.BooleanField(default=False),
                ),
                ("return_secondary_results", models.BooleanField(default=False)),
                ("consent_statements", models.TextField(default="")),
                (
                    "user_full_name_consent",
                    models.CharField(default="", max_length=200),
                ),
                (
                    "child_full_name_consent",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dependent_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consent_script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to="consentbot.consentscript",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentSession",
            fields=[
                (
                    "session_slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("current_node", models.CharField(max_length=100)),
                ("visited_nodes", models.JSONField(default=list)),
                ("responses", models.JSONField(default=dict)),
                ("workflow", models.CharField(blank=True, max_length=100, null=True)),
                ("num_test_tries", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consentbot.consentscript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentChatTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=32)),
                ("node", models.JSONField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consentbot.consentsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConsentTestAttempt",
            fields=[
                (
                    "attempt_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_try_num", models.IntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consent_script_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consentbot.consentscript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentTestAnswer",
            fields=[
                (
                    "answer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_node_id", models.CharField(max_length=64)),
                ("question_text", models.TextField()),
                ("user_answer", models.TextField()),
                ("answer_correct", models.BooleanField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="consentbot.consenttestattempt",
                    ),
                ),
            ],
        ),
    ]
