"""added user conversation caching

Revision ID: 00df0e0923fc
Revises: 3f32425dd5f2
Create Date: 2023-10-27 16:50:04.046002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00df0e0923fc'
down_revision = '3f32425dd5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_conversation_cache',
    sa.Column('cache_id', sa.String(length=36), nullable=False),
    sa.Column('workflow', sa.JSON(), nullable=False),
    sa.Column('current_node_id', sa.String(length=7), nullable=False),
    sa.Column('chat_url_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chat_url_id'], ['user_chat_url.chat_url_id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_conversation_cache')
    # ### end Alembic commands ###
