"""connected user model to chat model

Revision ID: 02c0f66c69ba
Revises: 41abf9155682
Create Date: 2023-10-11 17:48:45.081263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c0f66c69ba'
down_revision = '41abf9155682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_script_version_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'chat_script_version', ['chat_script_version_id'], ['chat_script_version_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_script_version_id')

    # ### end Alembic commands ###
