"""added user consent model

Revision ID: 0b87820ea3ed
Revises: 89a2742100f1
Create Date: 2023-11-06 10:53:24.957569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b87820ea3ed'
down_revision = '89a2742100f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
    sa.Column('user_consent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('store_sample_this_study', sa.Boolean(), nullable=False),
    sa.Column('store_sample_other_studies', sa.Boolean(), nullable=False),
    sa.Column('store_phi_this_study', sa.Boolean(), nullable=False),
    sa.Column('store_phi_other_studies', sa.Boolean(), nullable=False),
    sa.Column('return_primary_results', sa.Boolean(), nullable=False),
    sa.Column('return_actionable_secondary_results', sa.Boolean(), nullable=False),
    sa.Column('return_secondary_results', sa.Boolean(), nullable=False),
    sa.Column('consent_statements', sa.String(length=2000), nullable=False),
    sa.Column('user_full_name_consent', sa.String(length=200), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_consent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_consent')
    # ### end Alembic commands ###
