"""tracking number of test tries

Revision ID: 26fd77b3eda4
Revises: a7deb0c75ba4
Create Date: 2023-11-03 14:23:14.669863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fd77b3eda4'
down_revision = 'a7deb0c75ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_test_tries', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_try_num', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_test', schema=None) as batch_op:
        batch_op.drop_column('test_try_num')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('num_test_tries')

    # ### end Alembic commands ###
