"""added child full name to UserConsent

Revision ID: 3305da70fb52
Revises: 89f86ded0109
Create Date: 2023-11-17 16:18:40.044653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3305da70fb52'
down_revision = '89f86ded0109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_full_name_consent', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.drop_column('child_full_name_consent')

    # ### end Alembic commands ###
