"""renamed member columns again

Revision ID: 3c2639b6bb33
Revises: 6a543870378f
Create Date: 2023-11-30 16:22:38.256748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c2639b6bb33'
down_revision = '6a543870378f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='memberrolegroup'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('members_member_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('member_password')
        batch_op.drop_column('member_user_id')
        batch_op.drop_column('member_full_name')
        batch_op.drop_column('member_email')
        batch_op.drop_column('member_role')
        batch_op.drop_column('member_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('member_role', postgresql.ENUM('ADMIN', 'MEMBER', name='memberrolegroup'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('member_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('member_full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('member_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('member_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('members_member_email_key', ['member_email'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')
        batch_op.drop_column('password')
        batch_op.drop_column('full_name')
        batch_op.drop_column('email')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
