"""increased password length for hash

Revision ID: 408284d832fb
Revises: 3c2639b6bb33
Create Date: 2023-11-30 17:02:15.724466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408284d832fb'
down_revision = '3c2639b6bb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
