"""added User and Chat models

Revision ID: 41abf9155682
Revises: 
Create Date: 2023-10-05 23:04:50.510085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41abf9155682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('referred_by', sa.String(length=36), nullable=True),
    sa.Column('consent_complete', sa.Boolean(), nullable=False),
    sa.Column('enrolling_children', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_script_version',
    sa.Column('chat_script_version_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ),
    sa.PrimaryKeyConstraint('chat_script_version_id'),
    sa.UniqueConstraint('chat_id', 'version_number', name='_chat_version_uc')
    )
    op.create_table('user_chat_url',
    sa.Column('chat_url_id', sa.String(length=36), nullable=False),
    sa.Column('chat_url', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_url_id'),
    sa.UniqueConstraint('chat_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chat_url')
    op.drop_table('chat_script_version')
    op.drop_table('user')
    op.drop_table('chat')
    # ### end Alembic commands ###
