"""renamed admin to members

Revision ID: 465dc651d9a9
Revises: d8b9d58be400
Create Date: 2023-11-29 17:15:44.211009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465dc651d9a9'
down_revision = 'd8b9d58be400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_user_id', sa.String(length=36), nullable=False),
    sa.Column('member_email', sa.String(length=120), nullable=False),
    sa.Column('member_full_name', sa.String(length=200), nullable=False),
    sa.Column('member_password', sa.String(length=100), nullable=False),
    sa.Column('member_role', sa.Enum('ADMIN', 'MEMBER', name='memberrolegroup'), nullable=False),
    sa.PrimaryKeyConstraint('member_user_id'),
    sa.UniqueConstraint('member_email')
    )
    op.drop_table('admin_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('admin_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('admin_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('admin_full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('admin_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('admin_user_id', name='admin_users_pkey'),
    sa.UniqueConstraint('admin_email', name='admin_users_admin_email_key')
    )
    op.drop_table('members')
    # ### end Alembic commands ###
