"""revised user cache

Revision ID: 4c29f95bcacf
Revises: 26fd77b3eda4
Create Date: 2023-11-04 19:36:47.728104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c29f95bcacf'
down_revision = '26fd77b3eda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chat_cache',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('user_conversation_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_conversation_cache',
    sa.Column('cache_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workflow', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('current_node_id', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('chat_url_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_url_id'], ['user_chat_url.chat_url_id'], name='user_conversation_cache_chat_url_id_fkey'),
    sa.PrimaryKeyConstraint('cache_id', name='user_conversation_cache_pkey')
    )
    op.drop_table('user_chat_cache')
    # ### end Alembic commands ###
