"""renamed userfeedback column

Revision ID: 5332f29c3925
Revises: d464e2742189
Create Date: 2023-11-20 15:45:52.860290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5332f29c3925'
down_revision = 'd464e2742189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestions', sa.String(length=2000), nullable=True))
        batch_op.drop_column('improvement_suggestions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('improvement_suggestions', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.drop_column('suggestions')

    # ### end Alembic commands ###
