"""creating chat models

Revision ID: 87622aa543a8
Revises: 
Create Date: 2023-10-02 22:20:08.246729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87622aa543a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('chat_script_version',
    sa.Column('chat_script_version_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ),
    sa.PrimaryKeyConstraint('chat_script_version_id'),
    sa.UniqueConstraint('chat_id', 'version_number', name='_chat_version_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_script_version')
    op.drop_table('chat')
    # ### end Alembic commands ###
