"""tracking myself enrollment in user table

Revision ID: 89a2742100f1
Revises: 4c29f95bcacf
Create Date: 2023-11-06 09:44:37.891504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a2742100f1'
down_revision = '4c29f95bcacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrolling_myself', sa.Boolean(), nullable=False,
                                      server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('enrolling_myself')

    # ### end Alembic commands ###
