"""added children consent tracking

Revision ID: 89f86ded0109
Revises: 0b87820ea3ed
Create Date: 2023-11-11 16:03:55.274206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f86ded0109'
down_revision = '0b87820ea3ed'
branch_labels = None
depends_on = None


def upgrade():
    consent_age_group_enum = sa.Enum('LESS_THAN_SIX', 'SEVEN_TO_SEVENTEEN', 'EIGHTEEN_AND_OVER',
                                     'EIGHTEEN_AND_OVER_DEPENDENT', name='consentagegroup')
    consent_age_group_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_children_enrolling', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dependent_user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('consent_age_group', consent_age_group_enum, nullable=True))
        batch_op.create_foreign_key(None, 'user', ['dependent_user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP TYPE consentagegroup')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('consent_age_group')
        batch_op.drop_column('dependent_user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('num_children_enrolling')

    # ### end Alembic commands ###
