"""added created_at for follow up and feedback models

Revision ID: a6a7f1d060c5
Revises: 408284d832fb
Create Date: 2023-12-22 12:02:26.973404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a7f1d060c5'
down_revision = '408284d832fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_follow_up', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follow_up', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
