"""added UserTest table

Revision ID: a7deb0c75ba4
Revises: 00df0e0923fc
Create Date: 2023-10-31 18:49:11.747689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7deb0c75ba4'
down_revision = '00df0e0923fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_test',
    sa.Column('user_test_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_script_version_id', sa.String(length=36), nullable=False),
    sa.Column('test_question', sa.String(length=200), nullable=False),
    sa.Column('user_answer', sa.String(length=200), nullable=False),
    sa.Column('answer_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_script_version_id'], ['chat_script_version.chat_script_version_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_test_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_test')
    # ### end Alembic commands ###
