"""added userfollowup model and user consent decline

Revision ID: b96a1ba9dceb
Revises: 3305da70fb52
Create Date: 2023-11-20 10:22:22.120386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96a1ba9dceb'
down_revision = '3305da70fb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follow_up',
    sa.Column('user_follow_up_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('follow_up_reason', sa.String(length=200), nullable=False),
    sa.Column('follow_up_info', sa.String(length=200), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_follow_up_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined_consent', sa.Boolean(), nullable=False,
                                      server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('declined_consent')

    op.drop_table('user_follow_up')
    # ### end Alembic commands ###
