"""added userfeedback model

Revision ID: d464e2742189
Revises: b96a1ba9dceb
Create Date: 2023-11-20 15:37:48.279042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd464e2742189'
down_revision = 'b96a1ba9dceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('user_feedback_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('satisfaction', sa.String(length=25), nullable=True),
    sa.Column('improvement_suggestions', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_feedback_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    # ### end Alembic commands ###
