"""Added AdminUsers for authentication

Revision ID: d8b9d58be400
Revises: 5332f29c3925
Create Date: 2023-11-28 15:49:29.946482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b9d58be400'
down_revision = '5332f29c3925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('admin_email', sa.String(length=120), nullable=False),
    sa.Column('admin_full_name', sa.String(length=200), nullable=False),
    sa.Column('admin_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('admin_user_id'),
    sa.UniqueConstraint('admin_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_users')
    # ### end Alembic commands ###
