"""empty message

Revision ID: eb821fa20f39
Revises: 41abf9155682
Create Date: 2025-02-24 17:03:20.364269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb821fa20f39'
down_revision = '41abf9155682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='memberrolegroup'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('member_id', name=op.f('pk_members')),
    sa.UniqueConstraint('email', name=op.f('uq_members_email'))
    )
    op.create_table('user_chat_cache',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_user_chat_cache'))
    )
    op.create_table('user_consent',
    sa.Column('user_consent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dependent_user_id', sa.String(length=36), nullable=True),
    sa.Column('consent_age_group', sa.Enum('LESS_THAN_SIX', 'SEVEN_TO_SEVENTEEN', 'EIGHTEEN_AND_OVER', 'EIGHTEEN_AND_OVER_GUARDIANSHIP', name='consentagegroup'), nullable=True),
    sa.Column('store_sample_this_study', sa.Boolean(), nullable=False),
    sa.Column('store_sample_other_studies', sa.Boolean(), nullable=False),
    sa.Column('store_phi_this_study', sa.Boolean(), nullable=False),
    sa.Column('store_phi_other_studies', sa.Boolean(), nullable=False),
    sa.Column('return_primary_results', sa.Boolean(), nullable=False),
    sa.Column('return_actionable_secondary_results', sa.Boolean(), nullable=False),
    sa.Column('return_secondary_results', sa.Boolean(), nullable=False),
    sa.Column('consent_statements', sa.String(length=2000), nullable=False),
    sa.Column('user_full_name_consent', sa.String(length=200), nullable=False),
    sa.Column('child_full_name_consent', sa.String(length=200), nullable=True),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependent_user_id'], ['user.user_id'], name=op.f('fk_user_consent_dependent_user_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_user_consent_user_id_user')),
    sa.PrimaryKeyConstraint('user_consent_id', name=op.f('pk_user_consent'))
    )
    op.create_table('user_feedback',
    sa.Column('user_feedback_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('satisfaction', sa.String(length=25), nullable=True),
    sa.Column('suggestions', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_user_feedback_user_id_user')),
    sa.PrimaryKeyConstraint('user_feedback_id', name=op.f('pk_user_feedback'))
    )
    op.create_table('user_follow_up',
    sa.Column('user_follow_up_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('follow_up_reason', sa.String(length=200), nullable=False),
    sa.Column('follow_up_info', sa.String(length=200), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_user_follow_up_user_id_user')),
    sa.PrimaryKeyConstraint('user_follow_up_id', name=op.f('pk_user_follow_up'))
    )
    op.create_table('user_test',
    sa.Column('user_test_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_script_version_id', sa.String(length=36), nullable=False),
    sa.Column('test_try_num', sa.Integer(), nullable=True),
    sa.Column('test_question', sa.String(length=200), nullable=False),
    sa.Column('user_answer', sa.String(length=200), nullable=False),
    sa.Column('answer_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_script_version_id'], ['chat_script_version.chat_script_version_id'], name=op.f('fk_user_test_chat_script_version_id_chat_script_version')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_user_test_user_id_user')),
    sa.PrimaryKeyConstraint('user_test_id', name=op.f('pk_user_test'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined_consent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('enrolling_myself', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('num_children_enrolling', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('num_test_tries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chat_script_version_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_chat_script_version_id_chat_script_version'), 'chat_script_version', ['chat_script_version_id'], ['chat_script_version_id'])

    with op.batch_alter_table('user_chat_url', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_chat_url_chat_url'), ['chat_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chat_url', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_chat_url_chat_url'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_chat_script_version_id_chat_script_version'), type_='foreignkey')
        batch_op.drop_column('chat_script_version_id')
        batch_op.drop_column('num_test_tries')
        batch_op.drop_column('num_children_enrolling')
        batch_op.drop_column('enrolling_myself')
        batch_op.drop_column('declined_consent')

    op.drop_table('user_test')
    op.drop_table('user_follow_up')
    op.drop_table('user_feedback')
    op.drop_table('user_consent')
    op.drop_table('user_chat_cache')
    op.drop_table('members')
    # ### end Alembic commands ###
